dib-lab/khmer

ChangeLog
Makefile

See https://github.com/ged-lab/khmer/issues/729

no more --user installs

---

doc/dev/coding-guidelines-and-review.txt

@ctb @luizirber @camillescott ready for review and merge

add diff-cover & ChangeLog formatting requirements to checklist

---

ChangeLog
doc/dev/coding-guidelines-and-review.txt
khmer/__init__.py
khmer/_khmermodule.cc
sandbox/collect-variants.py
sandbox/correct-errors.py
sandbox/ec.py
sandbox/error-correct-pass2.py
sandbox/normalize-by-align.py
sandbox/read_aligner.py
tests/test_read_aligner.py

update ReadAligner to modern Python class + docs

---

ChangeLog
tests/test_scripts.py

Working on loading of counting table with bigcounts

---

ChangeLog

Remove empty script sandbox/sweep-paired-reads.py

---

ChangeLog
setup.py

work around versioneer bug

---

ChangeLog
sandbox/normalize-by-align.py
sandbox/read_aligner.py
sandbox/slice-reads-by-coverage.py

add copyright header Fix/797

---

ChangeLog
jenkins-build.sh

remove examples/stamps testing for now

---

ChangeLog
khmer/_khmermodule.cc

This slipped in during the _khmermodule.cc refactoring...

Fix coding style

---

ChangeLog
khmer/khmer_args.py
sandbox/unique-kmers.py

Add citation information for hll algorithm

---

ChangeLog
scripts/abundance-dist-single.py
scripts/count-overlap.py
tests/test_scripts.py

I have added the CSV option to the count-overlap.py and I added a test for this in test_scripts.py

Add csv option to count overlap.py

---

tests/test_counting_hash.py

updated memoryview test to skip on Py 2.6.2

---

ChangeLog
khmer/_version.py
setup.py

screed 0.8

---

ChangeLog
Makefile
doc/index.rst
doc/release-notes/index.rst
doc/release-notes/release-1.0.1.md
doc/release-notes/release-1.0.1.rst
doc/release-notes/release-1.0.md
doc/release-notes/release-1.0.rst
doc/release-notes/release-1.1.md
doc/release-notes/release-1.1.rst
doc/release-notes/release-1.2.md
doc/release-notes/release-1.2.rst
doc/release-notes/release-1.3.md
doc/release-notes/release-1.3.rst
doc/release-notes/release-1.4.md
doc/release-notes/release-1.4.rst
jenkins-build.sh

include releasenotes

---

ChangeLog
khmer/_khmermodule.cc

removes find_all_tags_truncate_on_abundance from python api

---

ChangeLog
lib/hashbits.cc

Added a few doxygen comments to hashbits.cc

---

ChangeLog
doc/index.rst
doc/release-notes/index.rst

small edit to release-notes; added repo to top of main docs page

---

ChangeLog
README.rst
doc/index.rst
doc/user/getting-help.rst
doc/user/index.rst

*draft* edits for "Supportability tasks #296," how to ask for help

started editing docs to add "how to get help"

---

ChangeLog
doc/conf.py

Disable smart rendering in Sphinx config (#958).

---

ChangeLog
doc/dev/getting-started.rst

clarified dev communication in getting-started.rst

---

.gitignore
ChangeLog
Makefile
khmer/khmer_args.py
oxli/__init__.py
oxli/build_graph.py
oxli/functions.py
scripts/load-graph.py
setup.py
tests/test_scripts.py

Initial oxli build using @ctb's API prototype found here: https://github.com/ctb/2015-experimental-graphalign/blob/445c200e662719c2bbf2f172a994ab6806d01edd/khmer_api.py

[Oxli] Initial oxli build 

---

scripts/normalize-by-median.py

So @bocajnotnef here you could replace normalize_by_median_and_check with several functions in Normalizer, build a new Normalizer for each input file, and then accumulate total/discarded in the outermost for loop across all the filenames.  Make some sense?
The basic idea is to replace globals with objects that "package" all of that information in one place.

try a class for the core processing bit of normalize-by-median

---

ChangeLog
khmer/_khmermodule.cc
khmer/_version.py
lib/hashbits.hh
lib/hashtable.hh
lib/labelhash.cc

Re-opened #1033 against master.

Refactor CPython layer so that CountingHash and Hashbits inherit from Hashtable.

---

scripts/normalize-by-median.py
tests/test_scripts.py

some comments and test rename

---

ChangeLog
khmer/_khmermodule.cc
lib/hashtable.cc
lib/hashtable.hh

Some C++ formatting errors got into the codebase in the last couple PRs, this fixes it before it snowballs.

astyle fixes

---

ChangeLog
lib/hashtable.cc

This tiny optimization addresses @ctb's comment about reducing the number of branches.

Small optimization to median_at_least

---

ChangeLog
Makefile
doc/dev/release.rst
khmer/thread_utils.py
scripts/do-partition.py
scripts/normalize-by-median.py
scripts/partition-graph.py
setup.cfg
setup.py
tests/test_counting_hash.py
tests/test_scripts.py
tests/test_threaded_sequence_processor.py

- setup.py was recompiling the module everytime (because zlib would be always compiled again)
- nose didn't stop on first error (setup.cfg)
- remove dependency on `future` (we were using it only for the queue/Queue stdlib module name change)

Remove some mistakes from py3 branch

---

ChangeLog
Makefile
doc/dev/getting-started.rst
jenkins-build.sh
scripts/readstats.py

update instructions for creating a new branch name to preferred practice

---

ChangeLog
setup.cfg

change the default test behavior to no longer stop on failed tests

---

ChangeLog
doc/dev/binary-file-formats.rst

My code-reading skills seem to have missed a step, and there's an error in the documentation for Countgraphs.
Cheers,
Kevin

Fix error in binary format documentation

---

ChangeLog
khmer/khmer_args.py
tests/test_functions.py
tests/test_normalize_by_median.py
tests/test_sandbox_scripts.py
tests/test_script_arguments.py

see https://github.com/dib-lab/khmer/issues/1125

Fixed tests output leak

---

ChangeLog
sandbox/README.rst
sandbox/collect-variants.py
sandbox/count-kmers-single.py
sandbox/count-kmers.py
sandbox/optimal_args_hashbits.py
sandbox/sweep-files.py
tests/test_sandbox_scripts.py

An initial implementation of a simple script to output k-mer counts.
Per request by @drtamermansour.

add scripts to output k-mers and k-mer counts

---

Makefile
jenkins-build.sh

Also set TESTATTR specifically in jenkins
@luizirber here's your PR :smile:

Use TESTATTR in makefile coverage

---

oxli/functions.py
sandbox/estimate_optimal_hash.py
tests/test_oxli_functions.py

for @bocajnotnef 
I still think both `estimate_optimal_with_*` functions can be merged into one, but it would be quite big (and clunky). Nevertheless, the names are too long to type, what about making an `optimal_size` function, take all `N`, `M` or `f` and then send the arguments to the correct function?
This PR has a small prototype for your appreciation.

Refactor suggestions for #1106

---

oxli/functions.py

Missed failing tests on one of my pulls; fixed here. See #1171 

Fixing failing master tests (#1171)

---

ChangeLog
khmer/kfile.py
oxli/functions.py
tests/test_normalize_by_median.py

fixes #1147 
@ctb @luizirber CR/merge please.

No more complaining about FIFO's being empty (addresses #1147)

---

ChangeLog
Makefile
khmer/__init__.py
khmer/khmer_args.py
oxli/build_graph.py
oxli/functions.py
scripts/abundance-dist.py
scripts/load-graph.py
scripts/normalize-by-median.py
scripts/readstats.py
tests/khmer_tst_utils.py
tests/test_hashbits.py
tests/test_normalize_by_median.py
tests/test_oxli_functions.py
tests/test_read_aligner.py
tests/test_subset_graph.py

Things sanitized:
```
- oxli/{functions,build_graph}.py
- scripts/{load-graph,normalize-by-median,abundance-dist}.py
```
things sedated:
```
- tests/{test_normalize_by_median,test_subset_graph}.py
```

Pylint Cleanup

---

tests/test_scripts.py
tests/test_streaming_io.py

Just unicode and exception syntax.

Fix py3 issues

---

ChangeLog
tests/khmer_tst_utils.py

Apologies for the push to master

check EGG-INFO for scripts

---

ChangeLog
README.rst
doc/index.rst
doc/roadmap.rst

Just documentation updates.
README.rst and doc/index.rst contain a lot of overlap; this PR cleans them up just enough for the release, see #1296 to discuss other options for later implementation.
@ctb, happy to self merge but wanted to give you an opportunity to review first.

refresh for 2.0

---

ChangeLog
khmer/_khmer.cc
lib/hashbits.hh
tests/test_nodegraph.py

Added function to retrieve the raw table data from Nodegraphs (née Hashbits).

add Nodegraph.get_raw_tables()

---

ChangeLog
khmer/__init__.py
lib/magic

update magic; add IANA approved media type

---

ChangeLog
lib/subset.cc

Check iterator before decrementing on repartition_largest_partition

---

.mailmap
ChangeLog
Makefile
doc/dev/a-quick-guide-to-testing.rst
doc/dev/getting-started.rst
doc/user/install.rst
jenkins-build.sh
pylintrc
pytest.ini
setup.cfg
setup.py
tests/khmer_tst_utils.py
tests/test_countgraph.py
tests/test_counting_single.py
tests/test_hll.py
tests/test_labelhash.py
tests/test_nodegraph.py
tests/test_normalize_by_median.py
tests/test_read_aligner.py
tests/test_read_handling.py
tests/test_read_parsers.py
tests/test_sandbox_scripts.py
tests/test_scripts.py
tests/test_version.py

Replace nose with py.test

---

ChangeLog
khmer/__init__.py
khmer/_khmer.cc
lib/hashtable.cc
lib/hashtable.hh
lib/kmer_hash.cc
lib/kmer_hash.hh
lib/read_aligner.cc
lib/subset.cc
lib/traversal.cc
lib/traversal.hh
scripts/do-partition.py
scripts/make-initial-stoptags.py
scripts/partition-graph.py
tests/test_countgraph.py
tests/test_counting_single.py
tests/test_hashset.py
tests/test_labelhash.py
tests/test_nodegraph.py
tests/test_subset_graph.py

Add a new CPython type, HashSet, to manage collections of hashes and tags.

---

CITATION
ChangeLog
doc/contributors.rst
doc/index.rst
doc/introduction.rst
doc/roadmap.rst
doc/whats-new-2.0.rst

Strip extraneous whitespace

---

.github/CONTRIBUTING.md
README.rst
doc/dev/codebase-guide.rst
doc/dev/coding-guidelines-and-review.rst
doc/dev/development.rst
doc/dev/release.rst
doc/index.rst
doc/introduction.rst
doc/roadmap.rst
doc/user/guide.rst
khmer/__init__.py
khmer/khmer_args.py
lib/oxli.pc.in
scripts/find-knots.py
setup.py

Updates to documentation

---

ChangeLog
khmer/_khmer.cc

Fix problems with using pointers to deallocated strings.

---

doc/user/blog-posts.rst

Added link to blog post

---

ChangeLog
tests/khmer_tst_utils.py
tests/test_countgraph.py
tests/test_filter_abund.py
tests/test_normalize_by_median.py
tests/test_read_handling.py
tests/test_sandbox_scripts.py
tests/test_scripts.py

formatted?
I'm kind of new to this whole github thing so hopefully this is how I would go about contributing these very simple changes.

Put copy_test_data in all but a few test functions as Issue #1405

---

ChangeLog
doc/dev/getting-started.rst

Add enchant to package manager install instructions

---

ChangeLog
scripts/filter-abund-single.py
tests/test_filter_abund.py

Fixes #1382
formatted?
Using https://gist.github.com/betatim/93a68b55a4d56f62df8393909a727102 to make the following plot:
Need to think briefly why the green is not perfectly on top of green.

Variable trimming for filter-abund-single.py

---

.travis.yml
ChangeLog

Start building with python3.5 on travis and enabled fast finishing.
formatted?

Added travis build on python3.5

---

ChangeLog
khmer/khmer_args.py

Update HLL citation

---

khmer/_khmer.cc
lib/Makefile
lib/alphabets.cc
lib/alphabets.hh
lib/assembler.cc
lib/assembler.hh
lib/hashtable.cc
lib/hashtable.hh
lib/khmer.hh
lib/kmer_filters.cc
lib/kmer_filters.hh
lib/subset.cc
lib/traversal.cc
lib/traversal.hh
setup.py

This branch builds on the work in #1412, which is under review. The wheel of science must keep turning!
After the introduction of the templated AssemblerTraversers, the original Traversal design seems clunky. Refactor this to be direction-templated and more appropriately named: a `Traverser` class still exists, but it wraps a `template <bool direction> class NodeGatherer` base which does most of what the previous `Traverser` did.
Tip filtering can be accomplished two possible ways: either throw away sub-contigs which deadend during the recursive contig gathering, _or_ make guess about which branches might be erroneous based on labels. For example, if a path originates from a high-coverage HDN and is only spanned by a single label, it's almost certainly a tip. Both will be tested.
The …

Open PR for building assembly features

---

examples/c++-api/count-demo.cc
khmer/_cpy_hashgraph.hh
khmer/_khmer.cc
lib/hashtable.cc
lib/hashtable.hh
lib/read_aligner.hh
lib/storage.cc
lib/storage.hh
lib/subset.cc
lib/subset.hh
lib/test-Colors.cc
lib/test-compile.cc

Covenience PR for updating #1504 with mass renaming.

Rename CountingHash to Countgraph and Hashbits to Nodegraph

---

ChangeLog
khmer/__init__.py
tests/test_functions.py

Primes should always be integers

---

ChangeLog
doc/dev/scripts-and-sandbox.rst

Fixes #1211.
<strike>- [ ] `make clean diff-cover` If it introduces new functionality in
`scripts/` is it tested?</strike>
formatted?
<strike>- [ ] Did it change the command-line interface? Only additions are allowed
major version number increment.</strike>
<strike>- [ ] Do the changes respect streaming IO? (Are they
tested for streaming IO?)</strike>

Documentation for standard/reserved command-line options

---

CHANGELOG.md
khmer/khmer_args.py
scripts/extract-paired-reads.py
scripts/fastq-to-fasta.py
scripts/filter-abund.py
scripts/interleave-reads.py
scripts/normalize-by-median.py
scripts/split-paired-reads.py
scripts/trim-low-abund.py
tests/test_streaming_io.py

Fix streaming gzip output

---

scripts/fastq-to-fasta.py

clean up ugly 'print' statement in fastq-to-fasta.py

---

tests/test_read_parsers.py

test that Read(..., quality=None) yields read w/o quality

---

tests/test_labelhash.py
tests/test_scripts.py

mark tests that will fail when run as root

---

khmer/__init__.py
khmer/khmer_args.py
oxli/build_graph.py

Follow up for my nitpicks from #1549 @standage 
formatted?

Follow up nitpicks for #1549

---

khmer/_khmer.cc
lib/hashtable.hh
tests/test_counttable.py

This is not a PR against master, but against refactor/hashing2. Added some documentation and some tests to verify expected behavior of tables with respect to non-ACGT sequence content. Currently this emits a C++ exception that is not properly handed off to Python (see https://github.com/dib-lab/khmer/issues/1541#issuecomment-274958013)

Some additions to refactor/hashing2

---

doc/dev/getting-started.rst
doc/index.rst

A pull into #1529 that fixes a few minor things.

minor fixes to update of getting-started docs.

---

khmer/_khmer.cc

Incrment -> Increment

---

lib/magic

not a python file

---

CHANGELOG.md
khmer/khmer_args.py
tests/test_script_arguments.py

suppress display of -x and -N on argparse help

---

doc/dev/getting-started.rst

Add reference to ORCID IDs to getting started docs

---

doc/dev/for-khmer-developers.rst

Add a comment on taking over stale PRs

---

.github/PULL_REQUEST_TEMPLATE.md
Makefile
doc/dev/getting-started.rst

Remove cppcheck as a developer tool

---

doc/conf.py
doc/requirements.txt

Reverts dib-lab/khmer#1630
Revert this for now, struggling to reproduce the error locally.

Revert "try out guzzle theme for documentation"

---

.travis.yml
examples/stamps/do.sh

A proposal for #1514
Seems pretty straight forward and a good test of sticking to the CLI API. Let's see how much it increases the travis run time.

Fix stamps example and add it to travis runs

---

doc/user/install.rst

Add sentence mentioning virtualenv option on HPC

---

khmer/khmer_args.py
scripts/abundance-dist-single.py
scripts/annotate-partitions.py
scripts/do-partition.py
scripts/extract-paired-reads.py
scripts/extract-partitions.py
scripts/filter-abund-single.py
scripts/filter-abund.py
scripts/filter-stoptags.py
scripts/load-into-counting.py
scripts/make-initial-stoptags.py
scripts/merge-partitions.py
scripts/normalize-by-median.py
scripts/partition-graph.py
scripts/readstats.py
scripts/trim-low-abund.py
scripts/unique-kmers.py

Fixes #1676. There are a few where I didn't add more docs because it seems not needed (e.g. --quiet)
formatted?

Add to CLI usage information

---

CHANGELOG.md
MANIFEST.in
doc/dev/release.rst
doc/user/known-issues.rst

Fixing a few things missed while going through the acceptance tests and release checklist.

A few small changes

---

author-skips.txt
authors.csv
doc/index.rst
doc/release-notes/release-2.1.md
doc/release-notes/release-2.1.rst

All of the acceptance tests passed! Woo hoo!
This PR brings in the release notes, and corrects one minor issue with the author list (a duplicated name). I will publish the release as soon as this PR is accepted.
Thanks everyone!!!

[MRG] Minor tweaks

---

.travis.yml
CHANGELOG.md
khmer/khmer_args.py
scripts/abundance-dist-single.py
scripts/load-into-counting.py
tests/test_scripts.py

This PR fixes a bug with conflicting flags in a couple scripts. It was fixed for master in #1723. This PR is for v2.1.
formatted?

Fix counting options bug a la #1723.

---

papers/paper.bib

Fixing CaSe sensitive bibtex entries

---

doc/user/install.rst

In response to #1810. Make a more prominent mention of C++11 and what that means in terms of compiler version.

[MRG] Mention C++11 requirement

---

.travis.yml

Trying to find out why docker still fails ...

[MRG] Debugging docker

---

doc/dev/getting-started.rst
doc/user/install.rst

The installation documentation is out of date and incorrect in places, as our recent rotation students will attest. This PR brings everything up to date. Closes #1830.
formatted?

[MRG] Fix install docs

---

.travis.yml
Makefile
docker/Dockerfile

We've had several cases over the last few months where the CI build (the Docker build in particular) failed for a contribution from the community or colleagues/collaborators without write access to the main repo. This PR fixes a bug in the Makefile and the Dockerfile and reads the full Github repository slug from `$TRAVIS_PULL_REQUEST_SLUG`.
Submitting this pull request from `standage/khmer` because obviously.
----------------------------------------
> <u>Message from the khmer maintainers</u>:
>
> *Please provide a description of the pull request above, including a
> reasonable level of detail and references to any relevant threads. After
> creating the  pull request, complete and mark the checklist below. If any item
> is not applicable, feel free to remove it or mark it as complete. If …

[MRG] Fix Docker build for CI
