- CONTRIBUTING.md
Since github adds the link to CONTRIBUTING.md when creating pull requests, I thought that the CONTRIBUTING.md should call out the checklist specifically.  An even cooler approach would be to modularize the text of the checklist block and include it in CONTRIBUTING.md and the docs, but my docs build foo isn't there yet. 
> Add link to PR checklist in CONTRIBUTING.md

- ChangeLog
- khmer/_khmermodule.cc
- tests/test_counting_hash.py
This is primitive functionality enabling certain sorts of queries into the graph from within Python. /cc @camillescott; at some point we should chat more about how this intersects with labeling.
> Added mechanisms for retrieving tags by position within a sequence

- ChangeLog
- scripts/split-paired-reads.py
- tests/test_scripts.py
Follow up to https://twitter.com/beconstant/status/560885880907243520
The script now imports the whole `os` module since `os.makedirs()` is being used.
> Enable specification of output directory

- ChangeLog
- scripts/split-paired-reads.py
- tests/test_scripts.py
Fixes #761, addresses most of https://github.com/ged-lab/khmer/issues/732#issuecomment-71903726 (although streaming won't work until the next release of screed).
> update split-paired-reads to support -1 and -2 options

- ChangeLog
- scripts/sample-reads-randomly.py
- tests/test_scripts.py
I met this error when the condition of that block of codes is satisfied, as below. I think this is a simple problem and the fix should work.
[qingpeng@dev-intel14 Subset]$ sample-reads-randomly.py -N 100 -M 12000 -R 1 -o test20000.fa.100 test20000.fa
|| This is the script 'sample-reads-randomly.py' in khmer.
|| You are running khmer version 1.3
|| You are also using screed version 0.7
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2014. http://dx.doi.org/10.6084/m9.figshare.979190
||
|| Please see http://khmer.readthedocs.org/en/latest/citations.html for details.
Subsampling 100 reads using reservoir sampling.
Subsampled reads will be placed in test20000.fa.100
opening test20000.fa for reading
... 10000 reads scanned
... 20000 …
> fix a glitch about string formatting in sample-reads-randomly.py

- ChangeLog
- doc/dev/coding-guidelines-and-review.txt
Fixed spellings in doc/dev/coding-guidelines-and-review.txt. Fixes issue #801.
> Corrected spelling errors in doc/dev/coding-guidelines-and-review.txt

- ChangeLog
- Makefile
- khmer/_khmermodule.cc
- tests/test_counting_hash.py
- tests/test_counting_single.py
- tests/test_hashbits_obj.py
- tests/test_labelhash.py
- tests/test_scripts.py
> recast std::bad_alloc as a Python exception

- ChangeLog
- doc/dev/index.txt
- doc/dev/scripts-and-sandbox.txt
A draft policy to reflect the issue raised in #471. Ready for review!
standard checklist:
And I'm also adding:
> Policies for sandbox/ and scripts/ code, together with a process for moving code into scripts/

- ChangeLog
- sandbox/calc-best-assembly.py
- sandbox/calc-error-profile.py
- sandbox/normalize-by-align.py
- sandbox/read_aligner.py
- sandbox/slice-reads-by-coverage.py
> Amend shebang line in sandbox scripts for python2

- ChangeLog
- scripts/interleave-reads.py
Currently, interleave-reads.py just prints the open file object. Now, it
will print output.name, i.e. the file path (or `<stdout>` for stdout)
> Make interleave-reads.py print output name nicely

- ChangeLog
- khmer/__init__.py
- khmer/_khmermodule.cc
- scripts/abundance-dist.py
- tests/test_counting_hash.py
- tests/test_hashbits.py
Update extension to pave the way for the future :wink:
PyLong instead of PyInt, Type initialization, PyBytes instead of PyString.
Replace common initialization with explicit type structs, and all types conform to the CPython checklist.
This fixes #38 and #728. The only item missing from #728 checklist is changing references from 'hash' to 'table' in all methods. All classes are also conforming to the CPython checklist.
TODO:
Remaining questions:
- Do we define `tp_new` for 'read-only' types, like `ReadPairIterator_Type` and `Read_Type`? They can't be constructed on Python land at the moment, and reflect internal components from C++ structures. (`khmer_KSubsetPartitionType` is also missing `tp_new`, but it is probably appropriate to deal with it in #802.)
- Missing documentation for …
> Some _khmermodule.cc refactoring

- ChangeLog
- khmer/__init__.py
- khmer/_khmermodule.cc
- lib/hllcounter.cc
- lib/hllcounter.hh
- lib/khmer_exception.hh
- setup.py
- tests/test_hll.py
HyperLogLog line coverage is a bit low because some conditions during estimation are not so easy to trigger. After exposing the HLL internals it was easier to find test cases using data already available for the current tests.
This PR improves the coverage and also simplifies some error checking inside the HLL.
> HLL coverage improvements

- scripts/abundance-dist-single.py
- tests/test_scripts.py
In abundance-dist-single.py: Use CSV format for the histogram. Includes column headers.
And add a test function for the --csv option in test_scripts.py
> CVS output to abundance-test-single.py

- ChangeLog
- scripts/load-into-counting.py
Hi all,
I confused myself this morning while trying to work out the effect of -b in load-into-counting.  Admittedly I was having a bit of a slow morning, but I got confused by the `--no-bigcounts (default=True)` help message. Does default=True mean that it's off or on by default?
This PR explains the behavior more verbosely in the help string, hopefully proofing against coffee deprived users :smile:.
Cheers,
K
> Make the help text of load-into-counting's '-b' flag more verbose

- ChangeLog
- khmer/_khmermodule.cc
- lib/counting.hh
- tests/test_counting_hash.py
This addresses #667: exposes the tables as a read-only buffer object. I've chosen read-only as there will be undefined behavior from writing directly to the tables outside of the `count` functions; of course, the idea is that you can still use the python-exposed hashtable object as you see fit, and the buffer view will update to reflect that.
For now, I've just exported a list of `N` buffers. Eventually I'd like this to properly define the buffer interface on the hashtable type object, exposing a single buffer or memoryview object with proper striding / offsets for the `N` dimension array, but... :effort:.
Some example usage:
```
In [1]: import khmer
In [2]: import numpy as np
In [3]: ht = khmer.new_counting_hash (20, 1e8, 4)
In [4]: tables = ht.get_raw_tables ()
In [5]: tables[0]
Out[5]: …
```
> Initial implementation of read-only buffer access to raw tables

- ChangeLog
- khmer/_khmermodule.cc
- tests/test_counting_hash.py
This addresses @luizirber's comment in #868 that python2.6 chokes on this test.
> Skip the get_raw_tables test if python doesn't  have memoryview

- ChangeLog
- khmer/kfile.py
- tests/test_functions.py
- tests/test_scripts.py
> Start of issue 718, file not existing clean up

- ChangeLog
- lib/counting.hh
Purely for convenience & efficiency.
I've been doing a lot of hacking on khmer in CPP land lately, and having to do `countinghash->get_tablesizes().size()` is quite verbose (and involves an inefficient vector copy doesn't it?).
Now, one can do `countinghash->n_tables()`, in the vein of `countinghash->n_entries()`.
> Add CountingHash::n_tables() accessor

- ChangeLog
- lib/hashbits.hh
Companion to #879
This adds `khmer::Hashbits::n_tables()` as a convenience method.
> Add n_tables accessor to Hashbits

- ChangeLog
- khmer/_khmermodule.cc
- lib/read_parsers.cc
- lib/read_parsers.hh
- tests/test_read_parsers.py
Hi all,
I've been thinking about #676, and decided to jump right in with one pre-requisite of metadata reporting, counting reads.
This is an implementation of read counting for the C++ parser(s), and an accessor for python-land objects.
It appears threadsafe, from my hacky testing (increments are done within spinlocked code blocks). I'll test further, and write tests etc as time permits :)
Cheers,
K
> Initial implementation of read counting in C++  read parser

- ChangeLog
- lib/hllcounter.cc
HLL merge method tried to be fancy and use std::transform instead of a for loop. Turns out the semantics changed for C++11, so it didn't work. Now works on C++11, and is probably simpler to understand too.
> Use for loop instead of transform

- ChangeLog
- khmer/_khmermodule.cc
- lib/read_parsers.cc
- lib/read_parsers.hh
- tests/test-data/truncated.fq
- tests/test_read_parsers.py
Half workaround, half bugfix
In #884, I noticed that truncated fastq files cause an empty read to be emitted from the parser. This throws an exception to work around this. Seqan fixes this in 2.0.
> Throw exception on weird seqan parsing of truncated file

- ChangeLog
- khmer/file.py
- scripts/load-into-counting.py
`make cppcheck`, and `make doc` output. Use `make format` and manual fixing as needed.
> Fix Issue 669: Check that output and info files in load-into-counting.py are writable before loading input

- ChangeLog
- scripts/filter-abund.py
Added file status checking `check_file_status()` for args.input_table in filter_abund.py
Not a documented issue, but found it while examining code for another issue.
> added check_file_status() for input_table

- ChangeLog
- doc/dev/getting-started.rst
Some clarifications in `doc/dev/getting-started.rst` for setting up a Conda environment instead of a virtualenv.
> Update getting started info for Conda users.

- ChangeLog
- khmer/__init__.py
- khmer/_khmermodule.cc
- lib/counting.cc
- lib/hashbits.cc
- lib/hashtable.cc
- lib/subset.cc
- tests/test_hashbits.py
- tests/test_scripts.py
> check for errors while writing to disk

- ChangeLog
- khmer/_khmermodule.cc
- lib/counting.cc
- tests/test_scripts.py
> add thread safety to CountingHash::abundance_distribtion

- .gitignore
- ChangeLog
- Makefile
- khmer/__init__.py
- khmer/kfile.py
- khmer/khmer_args.py
- khmer/thread_utils.py
- khmer/utils.py
- scripts/abundance-dist-single.py
- scripts/count-median.py
- scripts/count-overlap.py
- scripts/extract-long-sequences.py
- scripts/extract-paired-reads.py
- scripts/filter-abund-single.py
- scripts/filter-abund.py
- scripts/filter-stoptags.py
- scripts/find-knots.py
- scripts/galaxy/gedlab.py
- scripts/interleave-reads.py
- scripts/normalize-by-median.py
- scripts/readstats.py
- scripts/sample-reads-randomly.py
- scripts/split-paired-reads.py
- scripts/trim-low-abund.py
- setup.py
- tests/khmer_tst_utils.py
> Add pep257 targets to Makefile in preparation of docstrings cleanup.

- ChangeLog
- doc/dev/coding-guidelines-and-review.rst
> added Copyright queston to commit checklist

- ChangeLog
- khmer/__init__.py
- sandbox/collect-reads.py
- sandbox/collect-variants.py
- sandbox/saturate-by-median.py
- scripts/do-partition.py
- scripts/filter-abund-single.py
- scripts/load-graph.py
- scripts/load-into-counting.py
- scripts/normalize-by-median.py
- scripts/trim-low-abund.py
- tests/test_scripts.py
pull out error handling for too many collisions (table too small) into._init__.
Update tests to accommodate.
In filter abund, no threshold for max collisions listed--defaults to .2
Default is force=False. Force allowed in all places.
> Fix issue #21:  Refactor Hash Size Warning Logic into Common Module

- ChangeLog
- scripts/filter-abund-single.py
- scripts/normalize-by-median.py
- tests/test_scripts.py
fix: Fixes issue #58 Allows unpaired data to be included with paired data.
refactor: Pulls error handling for normalize into separate wrapper function.
> Fix Issuer #58: normalize-by-median: accept paired & unpaired data at the same time

- ChangeLog
- khmer/utils.py
- tests/test-data/old-style-format-w-comments.fq
- tests/test_scripts.py
Fix for the record parser to account for additional comments in old-style format records (/1) (#873)
> Parser fixes w/ respect to #873

- ChangeLog
- scripts/normalize-by-median.py
> Fixes issue #964 Scripts/normalize-by-median.py Don't pass ArgParseObject to functions

- ChangeLog
- doc/dev/scripts-and-sandbox.rst
- scripts/normalize-by-median.py
- scripts/trim-low-abund.py
Fixed #946 - ONLY stdout, stdin should be supported once #960 is merged
Fixed #947 as well by accidental commit to same branch.
> Added STDOUT streaming support for scripts/trim-low-abund.py

- ChangeLog
- doc/dev/a-quick-guide-to-testing.rst
- tests/khmer_tst_utils.py
in docstrings for khmer_tst_utils.py and in a-quick-guide-to-testing
> fixing docs to remind folks to make sure tests fail for the right reasons

- ChangeLog
- tests/test_scripts.py
splitting test_extract_long_sequences into 2 tests specific to fasta and fastq formats as described in issue #825
> split test for extract_long_sequences into test for fa and for fq

- ChangeLog
- scripts/load-into-counting.py
- tests/test_scripts.py
This PR adds a count of the total number of reads to the machine readable outputs of `load-into-counting.py` (TSV/JSONs).
It takes the sum of the number of reads processed from the `khmer.ReadParser` object which is used for hashing across all read files.
I've also bumped the "mrinfo_version" tag in the json output to 0.2.0, FWIW.
Cheers,
K
> Add total number of reads to summary json/tsv

- .gitignore
- ChangeLog
- Makefile
Just a few housekeeping things:
- `make clean` now uses `rm -f`, which doesn't print an error message if a file doesn't exist.
- Add coverage outputs to gitignore
> Clean up gitignore and make clean a little

- ChangeLog
- Makefile
Yo @mr-c,
I've been working on the libkhmer-dev package tonight, and found one issue in my earlier C++ lib PR. If you do `make lib` from the root makefile, nothing happens as `FORCE` is not used, and `./lib` already exists.
This just adds `FORCE` to that target.
Cheers,
Kevin
> Use FORCE in lib target of root makefile

- ChangeLog
- lib/Makefile
Hi all
Another minor change to `./lib/Makefile`.
The glob to remove shared objects during `make clean` only caught the current version, leading to an accumulation of old `libkhmer.so.$VERSION` in `./lib`. This remove all `*.so*` during make clean so this doesn't happen.
Cheers,
K
> Another silly Makefile PR: Make clean should remove all libkhmer.so versions

- ChangeLog
- tests/test_hll.py
The return values weren't being tested, add checks to existing tests.
> [HLL] Check return values fron consume_fasta and consume_string

- ChangeLog
- khmer/_khmermodule.cc
- lib/hashtable.cc
- lib/hashtable.hh
- scripts/normalize-by-median.py
- tests/test_counting_hash.py
- tests/test_scripts.py
Easy optimization to improve normalize-by-median: it's simple to observe that checking if the median of a set is greater than some cutoff is equivalent to checking if more than half the elements of that set are greater than some cutoff. The latter avoids doing a lookup for every kmer every time, and avoids a costly sort. On a small dataset (1m ecoli reads), this was an 18% performance improvement. Not bad for 5 minutes!
TODO: Add a couple tests
> Implement optimized median filter

- ChangeLog
- scripts/find-knots.py
- tests/test_scripts.py
> Add test for scripts/find-knots.py & associated fix

- ChangeLog
- Makefile
- lib/counting.cc
- setup.cfg
- tests/test_counting_hash.py
- tests/test_counting_single.py
- tests/test_hashbits_obj.py
- tests/test_labelhash.py
- tests/test_scripts.py
> Fix infinite loop in CountingHash gzipped IO

- ChangeLog
- tests/test_counting_hash.py
> fixed duplicated test    'get_kmer_counts_too_short' by changing to 'get_kmer_hashes_too_short'

- ChangeLog
- Doxyfile.in
- doc/dev/binary-file-formats.rst
- doc/dev/index.rst
Hi all,
This PR adds some personal notes I've taken from reading the source code on the binary file formats in khmer/oxli.
I'm not sure if it will be useful to the project, but here it is in any case. I'll polish it up a bit further, and maybe add some more formats, if you think it's useful.
Cheers,
K
> Developer-targeted detailed documentation of Oxli binary formats

- ChangeLog
- README.rst
https://virtualenv.pypa.io/en/latest/virtualenv.html#installation is a broken link, the new link is https://virtualenv.readthedocs.org/en/latest/installation.html I think...
> Fix link in readme to virtualenv installation instructions

- ChangeLog
- scripts/extract-paired-reads.py
- scripts/split-paired-reads.py
Fixes #1131 for me, and doesn't break the tests. But @ctb will may want to review it, to ensure I haven't nuked his original intentions of e29ce1a  :)
> Putative fix for file creation in CWD

- ChangeLog
- khmer/khmer_args.py
- tests/test_scripts.py
> removed incorrect warning for max_tablesize when -M is used

- ChangeLog
- tests/test_normalize_by_median.py
> disabled running of test_normalize_by_median_report_fp during normal tests

- ChangeLog
- lib/counting.hh
- lib/hashbits.hh
- lib/hashtable.hh
- lib/hllcounter.cc
- lib/hllcounter.hh
- lib/khmer_exception.hh
- lib/labelhash.cc
- lib/labelhash.hh
- lib/perf_metrics.hh
- lib/primes.hh
- lib/read_aligner.cc
- lib/read_aligner.hh
- lib/read_parsers.hh
- lib/subset.hh
- oxli/functions.py
- sandbox/collect-reads.py
- sandbox/count-kmers-single.py
- tests/test_counting_hash.py
- tests/test_counting_single.py
- tests/test_functions.py
- tests/test_normalize_by_median.py
- tests/test_script_arguments.py
Fix issues on master introduced recently:
- `sandbox/collect_reads.py` didn't have a default value for -C (set it to 50, based on docstring)
- xrange and cStringIO usage (not available on Python 3)
- Coding style issues (just ran `make format`)
> Fix Python 3 errors and coding style

- ChangeLog
- lib/counting.cc
- lib/hashbits.cc
- lib/hashtable.cc
- lib/labelhash.cc
- lib/subset.cc
`test_labelhash.py:test_load_wrong_filetype` is failing sometimes. It is somewhat hard to reproduce, but the issue is that the file signature can contain unprintable characters and the Python exception (`OSError`) is not being built properly.
This PR just print the char[4] string in hexadecimal. It is a bit weird, because the error message says it should be 'OXLI', which is not hexadecimal...
Previous (and this is non-deterministic, file signature can be different values):
`Incorrect file signature >a (m while reading labels/tags from tests/test-data/all-A.fa Should be: OXLI`
Now:
`Incorrect file signature 0x3e612028 while reading labels/tags from tests/test-data/all-A.fa Should be: OXLI`
> Escape incorrect signature as hex values

- ChangeLog
- oxli/functions.py
see https://github.com/dib-lab/khmer/pull/1126#discussion_r34310973
@mr-c @luizirber Merge, please?
> added --force check to #1126

- ChangeLog
- khmer/__init__.py
- scripts/normalize-by-median.py
- tests/test_normalize_by_median.py
This PR further refactors the diginorm script after #1010 and #1057.
Briefly,
* shifts tracking of sequences read/kept into the WithDiagnostics wrapper, which makes it much
more general (so e.g. I think we can reuse this code in trim-low-abund.py);
* allows for users setting the reporting frequency via the command line;
* exchanges the expensive modulus operator for a simple comparison watermark approach;
* the watermark approach allows for increments of more than one sequence, which allows for more correct reporting during broken-paired reading;
* adds lightweight tests for report_fp that can be run frequently;
> Refactor diginorm reporting

- ChangeLog
- tests/test_scripts.py
The test for the `--version` option & citation output is dynamically generated so as to avoid hard coding the lists of scripts that we provide. The folder the scripts get installed to may have other non-khmer scripts in them; this pull request ensures that we only test khmer scripts for khmer functionality by looking for the word 'khmer' on the second line of the script. This works due to the recent copyright audit #1289.
Currently the tests fail after installation from PyPI with `pip`. This PR fixes that.
> make version test more specific

- ChangeLog
- lib/hashbits.cc
- tests/test_nodegraph.py
Sequence Bloom Trees require merging bloom filters. Our implementation supports this, but does not properly track the number of occupied bins after doing so, which is necessary to calculate the FPR. This adds the feature to the update_from function on hashbits.
> Track occupied bins in hashbits

- ChangeLog
- scripts/normalize-by-median.py
- tests/test_normalize_by_median.py
> fix and test for close of --output file after first input file

- ChangeLog
- jenkins-build.sh
Fixes #1337 (wow, I should have used that issue for something cooler, so L33T).
I modified jenkins-build.sh to install codecov and upload the coverage reports that were already generated by coverage and gcovr. I also exposed a new variable on the Jenkins credentials, but this is not in any PR (I needed to change configuration in the server).
> Add codecov support in Jenkins

- ChangeLog
- tests/test_read_parsers.py
> fix syntax error introducing during pylint0 merge

- ChangeLog
- lib/hashtable.cc
- tests/test_countgraph.py
- tests/test_nodegraph.py
[substr()][1] second parameter should be the length of the substring, not the index of the last character to copy. There is another occurence at [lib/hashtable.cc][2] that needs to be checked.
[1]: http://www.cplusplus.com/reference/string/string/substr/
[2]: https://github.com/dib-lab/khmer/blob/ff7f047b5b0d9acb6c1eb73d54cfd39c9e3d1393/lib/hashtable.cc#L1265
> Fix: substr parameters

- ChangeLog
- khmer/_khmer.cc
- lib/hashtable.cc
- lib/hashtable.hh
- tests/test_countgraph.py
the existing function get_kmer_hashes returns all the hashes of all the k-mers in a string, in order; get_kmer_hashes_as_hashset returns them in a HashSet instead, which is much faster for certain use cases.
formatted?
> add get_kmer_hashes_as_hashset function

- khmer/khmer_args.py
- tests/test_script_arguments.py
Supports raw numbers and scientific notation (as before), but now also supports common suffixes.
- 1K: 1000 bytes (1 KB)
- 700m: 700,000,000 bytes (700 MB)
- 16G: 16,000,000,000 bytes (16 GB)
- 1.3T: 1,300,000,000,000 bytes (1.3 TB)
Upper- and lower-case single-letter suffixes are supported. I'd prefer to update the documentation after #1396 is merged.
------
formatted?
> Implement human-friendly memory request handling

- ChangeLog
- Makefile
- tests/test_scripts.py
The last PR introduced some PEP8 violations that I missed due to CI issues. This PR fixes those, and makes the `pep8` target a bit less verbose.
----------
formatted?
> PEP8 fixes

- .gitignore
- ChangeLog
- Makefile
- jenkins-build.sh
- setup.py
On OSX the `gcov` library doesn't exist. Modified the extension builder to strip out `gcov` from the list of libraries on OSX. With this change I am able to run `make diff-cover` on OSX and generate coverage reports 🎉 !
---
** should this be mentioned in the ChangeLog or is that for user facing changes only?
> Do not link against `gcov` on OSX when measuring coverage

- ChangeLog
- Makefile
- khmer/_khmer.cc
- khmer/_version.py
- lib/hashbits.hh
- lib/hashtable.cc
- lib/kmer_hash.cc
- lib/subset.cc
- lib/traversal.hh
- oxli/partition.py
- scripts/extract-partitions.py
- scripts/trim-low-abund.py
- tests/test_countgraph.py
- tests/test_hashset.py
After running `make format` for another PR I ended up with a clobbered `setup.py` and various other/unrelated files got modified. This is a PR that does nothing but execute those commands.
I also removed `setup.py` from the CPPSOURCES variable in `Makefile` otherwise `astyle` does its thing on it which leads to 😕.
Should jenkins be running `make format` and giving an error if it changes a file? Personally I prefer `pep8` as a guideline instead of hard rules, but then it is in the checklist for this project.
---
formatted?
> The style roller

- ChangeLog
- khmer/khmer_args.py
- scripts/filter-abund-single.py
- scripts/filter-abund.py
- scripts/normalize-by-median.py
- tests/test_normalize_by_median.py
Fixes parts of #1411
Started work on checking the range of counting args. This does not implement the "force and bigcount" part of #1411 
---
> [MRG] Error for counting args > 255

- .travis.yml
- ci_scripts/install.sh
- scripts/do-partition.py
Closes #1419.
First attempt to switch to travis for linux and OSX. Enabled travis on my fork and [it builds](https://travis-ci.org/betatim/khmer/builds/152684414)!
There are some failures on OSX that need investigating. And the whole set of diagnostic stuff needs adding as well.
---
> Switching to travis

- ChangeLog
- tests/test_filter_abund.py
> Remove for loops from test

- tests/test_sandbox_scripts.py
- tests/test_scripts.py
Fixes #1423.
Seems a bit ugly to have the code to generate the list of scripts at the top level.
formatted?
> Adapt to new py.test recommendation for yielding tests

- ChangeLog
- khmer/utils.py
- tests/khmer_tst_utils.py
- tests/test_functions.py
Fixes #1338.
This PR silently drops both reads if require_paired is set and one read is shorter than min_length.
formatted?
> A fix for a bug with require_paired & min_length in broken_paired_reader

- ChangeLog
- khmer/_khmer.cc
- lib/counting.cc
- lib/counting.hh
- lib/hashbits.cc
- lib/hashbits.hh
- lib/hashtable.hh
- lib/hllcounter.cc
- lib/hllcounter.hh
- lib/kmer_hash.cc
- tests/khmer_tst_utils.py
- tests/test_functions.py
In some places `HashIntoType` was used instead of a larger integer. This PR fixes that. While it makes no difference in the current stage as the two are synonyms in the future we will have a special type for hash values which is not equal to `uint64_t` anymore.
Prep work for #1444 
formatted?
> Refactor uint64_t vs HashIntoType

- ChangeLog
- khmer/khmer_args.py
- tests/test_script_arguments.py
formatted?
major version number increment.</strike>
tested for streaming IO?)</strike>
> Prevents -N from being set higher than 20. Override allowed by -f (fixes issue #1344)

- ChangeLog
- khmer/khmer_args.py
- tests/test_functions.py
- tests/test_script_arguments.py
These are changes from running `make format`, fixes some formatting stuff accumulated over previous PRs. Backs up @standage's point in #1447 that we should make these failures on travis.
formatted?
> Fix up formatting

- khmer/_khmer.cc
- tests/khmer_tst_utils.py
Add a layer of abstraction for converting hash values into python
objects (and back). This is in preparation for supporting our
own hash type that is not a plain integer.
---
formatted?
> Abstract hash <-> pyobject conversion

- .travis.yml
- ChangeLog
- tests/khmer_tst_utils.py
- tests/test_nodegraph.py
- tests/test_script_arguments.py
Moving to travis only. Following on from #1447 
This PR uploads coverage from travis, so we need to disable (that on) jenkins otherwise the reports from codecov will be useless.
This also makes `pep8` mandatory. We've been running `autopep8` on travis and asking people if they ran it but ever so often formatting errors sneak in.
`astyle` is a bit more tricky as I can not find a way to get it to return a non zero exit code when it does reformat stuff. Ideas/knowledge?
formatted?
> Travis all the way

- ChangeLog
- lib/counting.cc
- lib/hashbits.cc
- lib/hashtable.cc
- lib/labelhash.cc
- lib/subset.cc
Address #1368. There is a mismatch between gcc and system libs which makes it impossible to specifically catch an exception from ifstream::read; the problem is described on the gcc bugtacker:
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69877
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66145
This was previously only affecting a few users, but now affects the core devs :) the temporary measure is to just catch all exceptions in those places and hope for the best; a few times, we have to rethrow khmer exceptions to propagate them up.
formatted?
> Address the silly gcc bug

- ChangeLog
- lib/hashtable.cc
- tests/test_nodegraph.py
Currently calling `assemble_linear_path` with a seed _k_-mer that is not in the DBG will return the seed _k_-mer (or its reverse complement). I'm not sure if this is a feature or a bug, but I'd argue it's misleading. This PR treats it as a bug and returns an empty string if the seed _k_-mer is not in the DBG.
formatted?
- <strike>[ ] Did it change the command-line interface? Only additions are allowed
major version number increment.</strike>
- <strike>[ ] Do the changes respect streaming IO? (Are they
tested for streaming IO?)</strike>
> Fix linear path

- .travis.yml
- Makefile
- setup.cfg
Whitespace in arithmetic expressions is hard to read in slices. Fight the power.
formatted?
…whitespace
> use `make pep8` target in travis and rebel against fascist whitespace tyranny

- ChangeLog
- khmer/__init__.py
- khmer/_khmer.cc
- tests/test_read_parsers.py
Fixes #769 
This makes `khmer.Read` accessible from python land. If you do not set one of the attributes `hasattr` will return `False`.
formatted?
> Make `Read` accessible from python

- ChangeLog
- Makefile
- doc/requirements.txt
- Quirk 1: `doc/requirements.txt` forced `setuptools==3.4.1`, which is super old and breaks installations inside Anaconda (sometimes)
- Quirk 2: `pip` sometimes fails because it can't find a `easy_install.pth` inside the Anaconda `site-packages` (makes sense, no conda package should be installing it), and apparently the fix is to use the `--ignore-installed` flag. [Source](https://github.com/pypa/pip/issues/2751#issuecomment-165390180)
formatted?
> Fix two installation quirks

- ChangeLog
- doc/requirements.txt
Doc builds have been failing for a while (see e.g. [this])(https://readthedocs.org/projects/khmer/builds/4650703/) since we allowed newer version of autoprogram in doc/requirements.txt with
```
sphinxcontrib-autoprogram>=0.1.2
```
but the 0.1.3 release of autoprogram [breaks on python 2.7](https://bitbucket.org/birkenfeld/sphinx-contrib/issues/168/autoprogram-013-fails-on-python-27-due-to).  This PR fixes it by nailing autoprogram down to 0.1.2 which works ([see here](https://khmer.readthedocs.io/en/fix-rtd/)).
formatted?
> fix documentation build failure on ReadTheDocs from bad autoprogram version

- .travis.yml
- ChangeLog
Fixes #1512 
We need build-on-push to re-run travis when a PR is merged to generate
coverage information. Without this explicit whitelist we would
build every push to a PR related branch twice.
This PR goes together with toggling "build on push" in [the settings](https://travis-ci.org/dib-lab/khmer/settings). Did this for now.
nb. We need to do this bit of gymnastics because we use the origin
repo to also store the branches for PRs. A lot of projects keep those
in the user's repo so you can just flick the "build on push" switch in
the [travis config](https://travis-ci.org/dib-lab/khmer/settings)
> Whitelist master branch for travis build-on-push

- ChangeLog
- khmer/_khmer.cc
- khmer/utils.py
- lib/assembler.cc
- lib/hashbits.hh
- lib/hashtable.hh
- lib/read_parsers.hh
- lib/storage.hh
- scripts/extract-paired-reads.py
- scripts/filter-abund-single.py
- scripts/filter-abund.py
- scripts/sample-reads-randomly.py
- scripts/split-paired-reads.py
- scripts/trim-low-abund.py
- tests/test_assembly.py
- tests/test_read_handling.py
- tests/test_read_parsers.py
- tests/test_scripts.py
- tests/test_streaming_io.py
Fix #1098
and related to #1483 
After getting started on this I realised I wasn't sure how we wanted to use this. So far I am assuming the use case is to replace `utils.ReadBundle` as used in for example `trim-low-abund.py`.
Is it really worth it? We will end up turning all the screed `Records` into `read_parser::Read`s via various unicode -> bytes stuff, to then do some computation on them. In the current setup we pass the cleaned sequence to `get_median_count` and friends. Maybe there is something I am missing.
formatted?
ReadBundles group several Reads together.
> expose khmer.Read to python and use ReadParser in scripts

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- doc/dev/coding-guidelines-and-review.rst
- legacy/ChangeLog
This PR moves the existing ChangeLog into a legacy directory and replaces it with a new CHANGELOG.md file that is much more reasonable for what we need. It will be much less verbose, and include only substantial changes to khmer. Anything relevant to semantic versioning MUST be included, but under-the-hood changes can also be mentioned if they are suitably large and interesting.
We should still include this in the PR checklist, but maybe replace the message with something like "Are substantial changes documented in CHANGELOG.md?"
My prediction: merge conflicts will drop by > 75%.
Fixes #1457.
formatted?
<strike>- [ ] Did it change the command-line interface? Only additions are allowed
major …
> More reasonable change log format

- .github/PULL_REQUEST_TEMPLATE.md
- doc/dev/coding-guidelines-and-review.rst
See #1461. The notice needs only be added when new files are created, establishing copyright. Subsequent updates do not require changes to the initial notice establishing the initial claim of copyright. This will simplify the PR checklist.
<strike> - [ ] `make test` Did it pass the tests?
formatted?
> Stop it with the copyright updates

- khmer/utils.py
Calling functions is costly in python, so duplicate some short code instead of calling it.
```
$ time scripts/extract-paired-reads.py ecoli_ref-5m.fastq -s a.se -p a.pe
67.88s user 28.85s system 93% cpu 1:43.77 total
$ git checkout master
$ time scripts/extract-paired-reads.py ecoli_ref-5m.fastq -s a.se -p a.pe
78.75s user 30.85s system 93% cpu 1:57.20 total
```
Happy 🦃 day!
formatted?
> Speed up writing records

- sandbox/sweep-reads2.py
> Have sandbox/sweep-reads2 output FASTQ records when quality is present

- CHANGELOG.md
- khmer/khmer_args.py
- scripts/abundance-dist-single.py
- scripts/abundance-dist.py
- scripts/annotate-partitions.py
- scripts/count-median.py
- scripts/do-partition.py
- scripts/extract-long-sequences.py
- scripts/extract-paired-reads.py
- scripts/extract-partitions.py
- scripts/fastq-to-fasta.py
- scripts/filter-abund-single.py
- scripts/filter-abund.py
- scripts/filter-stoptags.py
- scripts/find-knots.py
- scripts/interleave-reads.py
- scripts/load-graph.py
- scripts/load-into-counting.py
- scripts/make-initial-stoptags.py
- scripts/merge-partitions.py
- scripts/normalize-by-median.py
- scripts/partition-graph.py
- scripts/readstats.py
- scripts/sample-reads-randomly.py
- scripts/split-paired-reads.py
- scripts/trim-low-abund.py
- scripts/unique-kmers.py
- tests/test_scripts.py
Fixes #1395
This introduces the `--info` command line flag. `scripts/filter-abund-single.py --info` now prints the citation information and then exits. This still prints the citation information when you run the script. This is a bit ugly because you have to specify what to cite twice (DRY). We can fix that by either getting rid of printing the citation info on every run or by moving things around. WDYT?
formatted?
New flag that prints citation information
> Add info flag to command line

- khmer/_khmer.cc
Fixes #1555 Missed a DECREF when converting to `HashIntoType`
formatted?
> Fix memory leak when converting to HashIntoType

- lib/oxli.pc.in
This PR does not touch the C++ or Python code. It only adds to line to the pkg-config template that allow pkg-config to output the correct flags for static linking. That makes it possible to develop against liboxli by, for example:
```bash
g++ -o test-prog-static -static -std=c++11 `pkg-config oxli --static --cflags` \
test-compile.cc `pkg-config oxli --static --libs`
```
> enable static building using pkg-config

- khmer/_khmer.cc
- lib/read_parsers.hh
- tests/test_read_parsers.py
Bring `khmer.Read` property names in line with those used by `screed`. Related to #1484 
formatted?
> Rename annotations to description

- CHANGELOG.md
- khmer/_khmer.cc
- lib/subset.cc
- tests/test_scripts.py
> Fix reading empty partition maps

- CHANGELOG.md
- khmer/_khmer.cc
- khmer/thread_utils.py
- khmer/utils.py
- lib/read_parsers.cc
- lib/read_parsers.hh
- scripts/extract-paired-reads.py
- scripts/filter-stoptags.py
- scripts/normalize-by-median.py
- tests/test_functions.py
- tests/test_read_handling.py
- tests/test_read_parsers.py
Compute the cleaned version of a read's sequence within the `Read` object.
This isn't ideal yet because the user of `Read` has to remember to call `set_cleaned_seq`. This is only a problem for c++ users, in python we can automate this. In c++ it is difficult because of the way `seqan` works which gets access directly to the sequence member of `Read` (we can't make it private).
formatted?
> Add  cleaned_seq attribute to `Read` class

- doc/dev/python-api.rst
Some additions to the python API docs started in `refactor/hashing2`.
> Add to python API documentation

- doc/dev/coding-guidelines-and-review.rst
Related to #1574. When looking for docs on the minimum gcc version I found that the docs already contain info. Added a sentence stating which version we use on travis.
formatted?
> Add coment about gcc version requirement

- CHANGELOG.md
- khmer/_cpy_hashgraph.hh
- khmer/_khmer.cc
- lib/assembler.cc
- lib/assembler.hh
- lib/hashgraph.cc
- lib/hashgraph.hh
- lib/hashtable.cc
- lib/hashtable.hh
- lib/hllcounter.cc
- lib/hllcounter.hh
- lib/khmer.hh
- lib/labelhash.cc
- lib/labelhash.hh
- lib/read_parsers.cc
- lib/read_parsers.hh
- lib/subset.cc
- lib/traversal.cc
- lib/traversal.hh
I originally explored this approach in #1451, but got stuck on the templating details. After giving this a rest for a few months, I revisited today and have been able to address the linker issues that plagued me before. I had hoped to avoid using pointers altogether and take a more explicit approach, but this turned out to be untenable. Instead I transitioned to the use of smart pointers with read parsers.
This PR doesn't add BAM support, but it lays the groundwork to do so!
Remaining:
-----
formatted?
tested for streaming …
> Support for different input formats using templates: take 2

- CHANGELOG.md
- scripts/trim-low-abund.py
Issue #1402 manifests itself consistently on various HPC systems, both in the tests and when `trim-low-abund.py` is run interactively. I've had a few successful runs now by simply commenting out the code that deletes the temp directory at the end of the script. This PR puts a little bit of lipstick on that pig, making a backwards-compatible addition to the command-line interface. This (hopefully) isn't a permanent solution, but I don't have the time or interest to research the problem more thoroughly right now.
formatted? …
> Catch error trying to delete tempdir on NFS

- khmer/_khmer.cc
- lib/read_parsers.cc
- lib/read_parsers.hh
- scripts/trim-low-abund.py
Fixes #1603 which also solves #1602 
Needs someone with NFS access to test that this really solves the problem.
formatted?
> Add close method to ReadParser

- .travis.yml
- Makefile
Addresses https://github.com/dib-lab/khmer/pull/1511#issuecomment-279251128 where @ctb noticed that we do not generate coverage for c++ code anymore.
> Fix generation of coverage for c++ code

- Makefile
- setup.py
Potentially fixes #1611 
formatted?
> Add missing header to build dependency

- doc/user/choosing-table-sizes.rst
- switched from scientific notation to human-readable
- added section for `unique-kmers.py` and `-U` option (closes #1558)
- updated diginorm FPR threshold from 10% to 20%
Any comments on this last point? The default threshold for normalize-by-median is 0.2, and it seems like we either need to update the docs to reflect this or change the threshold if the docs are correct. Unless I'm missing somthing.
> Updated docs for setting memory

- .travis.yml
Fixes #1647 For some reason `make doc` fails on travis but not locally. Trying to find out why.
> `make doc` fails on travis

- khmer/khmer_args.py
- scripts/abundance-dist-single.py
- tests/test_nodegraph.py
- tests/test_script_arguments.py
Fixes #1408 
Sometimes you want a Nodegraph with roughly the same number of
buckets as a Countgraph you are using.
Is having the number of buckets in the `Nodegraph` match those of the `Countgraph` actually what people want?
Still needs a bit of fine tuning/understanding how/why the sizes differ slightly in the two cases (`-x` vs `-M`).
There is also the option that we interpret `-M` as the absolute upper total memory used by everything in this script. In which case we need to be a bit smarter when calculating table sizes as they have to take into account what comes later in the script. Essentially making it specific for each script :-/
formatted?
formats also requires a major version number …
> [MRG] Add function to calculate Nodegraph size matched to a Countgraph

- lib/read_parsers.hh
- tests/test_nodegraph.py
`consume_partitioned_fasta` raises `khmer_exception` and not `khmer_value_exception` when consuming an unpartitioned file. `khmer_exception` is, however, unhandled at the Python layer. This fixes the exception.
formatted?
> write test for consume_partitioned_fasta on unpartitioned file

- .mailmap
- MANIFEST.in
- doc/dev/release.rst
- sort-authors-list.py
Updated the sort-authors script to use python3 and went
through the beginning of the checklist.
Fixes #1403 #1646 #372
formatted?
> Update release checklist

- setup.py
- tests/test_read_parsers.py
This updates khmer master to work with screed master (as well as https://github.com/dib-lab/screed/pull/64).
It will have to wait to be merged until we release a new version of screed though :). We should then update khmer master to require the new version of screed.
formatted?
> correct test of screed.Record to use name/sequence and not 'dict' in constructor

- .travis.yml
- lib/read_parsers.cc
- tests/test_read_parsers.py
Fixes #1666 and #1119 
Update the error message to give the user a better chance of figuring out what the problem is.
Right now we can't tell the difference between a file that doesn't exist and a file that contains nonsense. Looking into detecting the difference between these two cases.
formatted?
> [MRG] Add tests for corrupted FASTA file content

- scripts/trim-low-abund.py
- tests/test_scripts.py
Fixes #973 Change log output to inform user that data has been streamed to
stdout or explicitly named files, isntead of using a generic
message.
formatted?
> [MRG] Update log info for trim-low-abund

- CHANGELOG.md
- scripts/trim-low-abund.py
- tests/test_scripts.py
Related to #974 and #975. This lets the user output a file recording information about the run to a JSON or TSV file.
formatted?
> [MRG] Add support for run time info to json or tsv in trim-low-abund

- tests/test_scripts.py
Fixes #975
Explicitly check that the output of trim-low-abund can be parsed as
FASTA when it is being redirected to stdout.
formatted?
> Add test that parses stdout from trim-low-abund.py

- Makefile
Fixes #1552
I added a comment in the Makefile pointing people at `setup.{py,cfg}`. That is the place to edit stuff if you want to influence how things are compiled. The variables in `Makefile` are only used by `cppcheck` but I guess most people start by looking in the `Makefile` and then get confused why it doesn't seem to do anything. Ideally we could extract the values from `setup.cfg` instead of duplicating them, but my `distutils` foo is not strong enough for that. Any ideas?
formatted?
> Add comment to the Makefile to document where to change things

- CHANGELOG.md
- khmer/__init__.py
- lib/hashtable.cc
- lib/hashtable.hh
- lib/khmer.hh
- lib/storage.cc
- tests/test_counttable.py
- tests/test_nibblestorage.py
- tests/test_tabletype.py
Fixes #1659 `SmallCounttable` uses murmurhash now. We can't inherit from `Counttable` because that would lock us into the storage used by that. So went with the approach of copying the hashing stuff.
Does someone know if having mixins works as nicely in c++ as it does in python? Then we could have a `MurmurHashMixin` to add the functionality.
formatted?
> [MRG] Switch SmallCounttable to murmurhash

- lib/assembler.cc
- lib/assembler.hh
- lib/kmer_filters.cc
- lib/kmer_filters.hh
- lib/traversal.cc
- lib/traversal.hh
- tests/test_assembly.py
A more comprehensive version of #1680. Removes NonLoopingAT entirely, instead merging its functionality in to LinearAssembler.
formatted?
> Cherry pick merger of AssemblerTraverser with NonLoopingAT

- Makefile
The `make install-dep` target installs dev dependencies. We should avoid conflicts and let setuptools handle the screed dependency.
- [x ] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
formatted?
> Let setup.py handle screed dependency

- papers/paper-v2.1.md
Fixes links in Markdown for JOSS v2.1 paper. See https://github.com/openjournals/joss-reviews/issues/272#issuecomment-306649961.
> Fix links in paper markdown

- .travis.yml
- CHANGELOG.md
- Makefile
- ci_scripts/install.sh
- doc/index.rst
- khmer/__init__.py
- khmer/_oxli/assembly.pxd
- khmer/_oxli/assembly.pyx
- khmer/_oxli/graphs.pxd
- khmer/_oxli/graphs.pyx
- khmer/_oxli/hashing.pxd
- khmer/_oxli/hashing.pyx
- khmer/_oxli/hllcounter.pxd
- khmer/_oxli/hllcounter.pyx
- khmer/_oxli/parsing.pxd
- khmer/_oxli/parsing.pyx
- khmer/_oxli/traversal.pxd
- khmer/_oxli/utils.pxd
- khmer/_oxli/utils.pyx
- setup.py
Addresses #1769 
Removes the travis builder, sets the minimum version in setup.py, adds cython directives (including language_level) to setup.py, changes imports to absolute in pyx files for Python 3.
formatted?
> Drop Python 2 Support

- include/oxli/hashgraph.hh
- include/oxli/hashtable.hh
- include/oxli/oxli.hh
- include/oxli/storage.hh
- khmer/_oxli/oxli_types.pxd
- tests/test_subset_graph.py
`std::unordered_map` has O(1) amortized random access; `std::map` is O(log(n)), due to maintaining internal ordering of its elements. Most of our use cases don't require that ordering, so this switches them to `unordered_map` where appropriate. On map sizes on the order of 5 million elements, this is a 20x speedup for element access. For large datasets using `bigcount`, I imagine the benefit will be... considerable.
cc @ctb @luizirber @betatim 
formatted?
> Convert to unordered_map where appropriate

- include/oxli/hashtable.hh
Switch QFCounttable to use murmur hash. This makes it somewhat more predictable when the QF will be "full", see https://github.com/dib-lab/khmer/issues/1751#issuecomment-329535858
Should we modify the CQF code to raise an exception instead of using an assert or is there a way to "catch" an assert? This way we can print a better message for the user when we do exhaust the available slots. An alternative would be to check every time we insert a kmer if all slots are used :-/
formatted?
> [MRG] Switch QFCounttable to murmurhash

- src/oxli/hashgraph.cc
- tests/test_nodegraph.py
This fixes a fun bug where `Hashgraph::traverse_linear_path` added the last linear node in a path into the stop bloom filter, rather than adding the high-degree node(s) that bookended the linear path.  This meant that attempts to assemble the linear paths afterwards were often truncated.
The tests have been updated to check this as well.
formatted?
> [MRG] add HDN into stop filter, not end of linear path

- tests/test_assembly.py
I was unable to find a test that checked to make sure that `LinearAssembler.assemble(...)` can take a hash (see #1765) so I wrote one.
Fixes #1765 (or at least makes sure it stays fixed :).
formatted?
> [MRG] add a test to make sure that LinearAssembler.assemble takes hashes

- src/oxli/hashtable.cc
Clearing the string containing the sequence is not needed and was
happening too early (before the end of the loop).
Noticed this because when working on the rolling hash. For one of the unit tests the first character in the sequence would suddenly be `\0` which "breaks everything".
Any ideas how we can test for this explicitly? I don't :(
> [MRG] Remove clearing of sequence

- setup.py
The current `setup.py` file is a bit schizophrenic with respect to Cython. The `cythonize` function is conditionally imported, but is unconditionally called. This makes it impossible for packaging and installation systems without cython installed to even parse the file without failing.
This pull request introduces a temporary fix to this problem by making the call to `cythonize` conditional and then adding Cython as an explicit setup requirement.
Eventually we'll want to do this more cleanly, but for now this PR fixes #1783 and similar problems where calling Cython without making sure it's installed can be problematic.
> [MRG] Stopgap for conditional cython import

- include/oxli/hashtable.hh
- khmer/_oxli/graphs.pyx
- khmer/_oxli/hashset.pyx
- khmer/_oxli/traversal.pyx
- src/oxli/hashgraph.cc
- tests/test_hashset.py
- tests/test_nodegraph.py
Some spotty patches to keep objects from being evaluated or converted prematurely; fixes a major performance regression noted in spacegraphcats (#1805).
* make graph.neighbors(...) return Kmers;
* traverse_linear_path now returns HashSets rather than sets;
* HashSet __contains__ now uses std::set::find instead of full enumeration;
Fixes #1806 #1805 #1807.
formatted?
> [MRG] Some performance hacks and minor fixes on graph interface

- .travis.yml
- docker/Dockerfile
- setup.cfg
Fixes #1777 by switching from TRAVIS_PULL_REQUEST_SHA which can be empty to TRAVIS_COMMIT.
This might also fix the build error in #1801.
> [MRG] Switch to use TRAVIS_COMMIT instead of TRAVIS_PULL_REQUEST_SHA

- setup.py
Edits setup.py to remove unnecessary calls to `cythonize` (such as during `clean`). Uses the `Extension` class provided by Cython, falling back to the regular one from setuptools if Cython isn't installed.
formatted?
> Cythonization Improvements

- tests/test_read_aligner.py
Tests using `yield` were addressed in #1430, but since then I continue to get warnings about yield tests being deprecated. This PR cleans up the read aligner tests just a teensy bit. There were several tests whose first statement was `return  # CTB`, presumably as a shortcut to marking the test as `known_failing`. I removed these statements and instead used pytest's canonical mechanism to mark these as `known_failing`. However, this was still not enough to make the deprecation warning go away for the `test_align_read_new` function. So I cleaned that up a bit.
This PR doesn't identify or fix any problems with the read aligner functionality, but it reduces noise that has become a cognitive burden to remember to ignore, at least for me.
> [MRG] Purge yield tests

- authors.csv
I hate that it has come to this, but it looks like unless we want to do a lot of troubleshooting and hacking on pip itself, the easiest way to get rid of khmer's build issues with the Python3 toolchain is to remove non-ASCII characters from the author list (temporarily hopefully). See https://github.com/dib-lab/khmer/issues/1565#issuecomment-354156725.
> [MRG] Unicode --> ASCII for contributor names

- tests/test_sandbox_scripts.py
Related to Issue #1839
removed stderr and changed to capsys
formatted?
> change stdout-err to capsyd

- doc/requirements.txt
This PR specifies a new minimum version number of one of the sphinx plugins we use to avoid doc build failures. Closes #1841.
Ready for review and merge!
> [MRG] Specify new min version for sphinx plugin

- .github/PULL_REQUEST_TEMPLATE.md
Following up on #1822, this PR updates the PR checklist and removes several items that are being ignored or have been satisfied in other ways. I've attempted to make the new checklist descriptive as to our current process, rather than prescriptive about what that process should be. I think it's a fairly reasonable compromise between what we should expect of new contributors and what we should remind frequent contributors to do without too much chafing.
Closes #1822.
Ready for discussion (and review and merge)!
> [MRG] Relax the PR checklist

- khmer/_oxli/graphs.pyx
- tests/test_counttable.py
The `primes` argument of Countgraph and Nodegraph is useful for creating a sketch with the same exact size as another sketch. Somehow this functionality never got ported over to the *table sketch types, and this PR fixes that oversight.
Ready for review and merge!
----------------------------------------
`make clean diff-cover` or the CodeCov report that is automatically
generated following a successful CI build.)
> [MRG] Endow *table sketch types with 'primes' argument

- CHANGELOG.md
- scripts/trim-low-abund.py
In `trim-low-abund.py`, use the full path of the input filename rather than only the basename, in case of identical basenames which causes errors.
`make clean diff-cover` or the CodeCov report that is automatically
generated following a successful CI build.)~
Only backwards-compatible additions are allowed without a major version
increment. Changing file formats also requires a major version number
increment.
[keepachangelog](http://keepachangelog.com/) for more details.
> use full path for temporary filename

- setup.py
This PR updates the min OS X build target. 10.7 is very old and the setuptools/distutils build config for 10.7 uses outdated compiler options. Latest OS X release is 10.14, but even just updating to 10.9 as the min build version enables a proper build on recent versions.
> Fix build for OS X
